language: go

go:
 - tip

before_script:
  - $BASE_PACKAGE=github.com/eddogola/unsplash-go
  - $UNSPLASH_PACKAGE=$BASE_PACKAGE+/unsplash
  - $CLIENT_PACKAGE=$UNSPLASH_PACKAGE+/client
  - $EXAMPLE_PACKAGE=$UNSPLASH_PACKAGE+/example
  - $UTILS_PACKAGE=$UNSPLASH_PACKAGE+/utils
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck

script:
 - cd unsplash
 - go test -race -v -coverprofile=coverage.txt -covermode=atomic .
 - go vet .
 - staticcheck $UNSPLASH_PACKAGE
 - staticcheck $CLIENT_PACKAGE
 - staticcheck $EXAMPLE_PACKAGE
 - staticcheck $UTILS_PACKAGE
 - golint -set_exit_status $(go list)

after_success:
  - bash <(curl -s https://codecov.io/bash)