language: go

go:
 - tip

env:
  - BASE_PACKAGE=github.com/eddogola/unsplash-go
  - UNSPLASH_PACKAGE=$BASE_PACKAGE+/unsplash
  - CLIENT_PACKAGE=$UNSPLASH_PACKAGE+/client
  - EXAMPLE_PACKAGE=$UNSPLASH_PACKAGE+/example
  - UTILS_PACKAGE=$UNSPLASH_PACKAGE+/utils

before_script:
  - $GO_FILES=$(find . -iname '*.go' -type f)
  - go get -u golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
  - go get github.com/fzipp/gocyclo/...

script:
 - test -z $(gofmt -s -l $GO_FILES)     #Fail if a .go file hasn't been formatted with gofmt
 - cd unsplash
 - go test -race -v -coverprofile=coverage.txt -covermode=atomic .
 - go vet .
 - staticcheck $UNSPLASH_PACKAGE
 - staticcheck $CLIENT_PACKAGE
 - staticcheck $EXAMPLE_PACKAGE
 - staticcheck $UTILS_PACKAGE
 - gocyclo -over 19 $GO_FILES
 - golint -set_exit_status $(go list)

after_success:
  - bash <(curl -s https://codecov.io/bash)